# Generated by Django 4.0.3 on 2022-04-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('first', 'Анкета первой категории значимости'), ('second', 'Анкета второй категории значимости'), ('third', 'Анкета третей категории значимости'), ('without', 'Анкета без категории значимости'), ('determine', 'Анкета определения категории значимости')], max_length=200, unique=True)),
                ('fields', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('type_used_systems', models.CharField(max_length=100)),
                ('questionnaire_title', models.CharField(max_length=100)),
                ('done_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_title', models.CharField(max_length=100)),
                ('report', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('type_used_systems', models.CharField(max_length=100)),
                ('done_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
