# Generated by Django 4.0.3 on 2022-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('security', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('fields', models.TextField()),
            ],
        ),
    ]
