# Generated by Django 4.0.3 on 2022-03-27 20:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('security', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('start', 'Старторая анкета'), ('first', 'Анкета первой категории значимости'), ('second', 'Анкета второй категории значимости'), ('third', 'Анкета третей категории значимости'), ('without', 'Анкета без категории значимости'), ('determine', 'Анкета определения категории значимости')], max_length=200, null=True)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, null=True, size=None)),
            ],
        ),
    ]
