# Generated by Django 4.0.3 on 2022-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
