# Generated by Django 4.0.3 on 2022-03-27 20:55

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_Questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fields',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, null=True, size=None, validators=[main.validators.validate_questionnaire_fields]),
        ),
    ]
