# Generated by Django 4.0.3 on 2022-03-27 19:38

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AlterField(
            model_name='questionnaire',
            name='fields',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
