# Generated by Django 4.0.3 on 2022-03-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questionnaire_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='fields',
        ),
    ]
