# Generated by Django 4.0.3 on 2022-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionnaire_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='mode',
            field=models.CharField(choices=[('determine', 'Анкета определения категории'), ('simple', 'Обычная анкета')], default='simple', max_length=200),
        ),
    ]
