# Generated by Django 4.0.3 on 2022-03-27 19:47

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_questionnaire_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='fields',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
