# Generated by Django 4.0.3 on 2022-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_questionnaire_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
