# Generated by Django 4.0.3 on 2022-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userorganizationinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fields',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(blank=True, choices=[('start', 'Старторая анкета'), ('first', 'Анкета первой категории значимости'), ('second', 'Анкета второй категории значимости'), ('third', 'Анкета третей категории значимости'), ('without', 'Анкета без категории значимости'), ('determine', 'Анкета определения категории значимости')], max_length=200),
        ),
    ]
