# Generated by Django 4.0.3 on 2022-03-28 13:34

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_questionnaire_fields_alter_questionnaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fields',
            field=models.TextField(blank=True, validators=[main.validators.validate_questionnaire_fields]),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(blank=True, choices=[('first', 'Анкета первой категории значимости'), ('second', 'Анкета второй категории значимости'), ('third', 'Анкета третей категории значимости'), ('without', 'Анкета без категории значимости')], max_length=200),
        ),
    ]
