# Generated by Django 4.0.3 on 2022-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_questionnaire_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_title', models.CharField(max_length=100)),
                ('report', models.TextField()),
            ],
        ),
    ]
