# Generated by Django 4.0.3 on 2022-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='done_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-12 12:12:12'),
            preserve_default=False,
        ),
    ]
