# Generated by Django 4.0.3 on 2022-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_report_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fields',
            field=models.TextField(),
        ),
    ]
